// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uW8gvugjoKeK9SUGHJ1xTT
// Component: yCdWSm9bT4c
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import IconLink from "../../IconLink"; // plasmic-import: Cdz9E6C5eqt/component
import TextInput from "../../TextInput"; // plasmic-import: SwBTk4bUPNYv/component
import Button from "../../Button"; // plasmic-import: gebML7xSHzTG/component
import { useScreenVariants as useScreenVariantsnAsWzyTlUgH } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: NAsWZYTl_UgH/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_simple_light_landing_page.module.css"; // plasmic-import: uW8gvugjoKeK9SUGHJ1xTT/projectcss
import sty from "./PlasmicFooter.module.css"; // plasmic-import: yCdWSm9bT4c/css
import LogoIcon from "./icons/PlasmicIcon__Logo"; // plasmic-import: 9c44qOsIkW6_/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: avmT2ajzT5Xl/icon
import TwitterIconIcon from "./icons/PlasmicIcon__TwitterIcon"; // plasmic-import: YeOdxYamEIAn/icon
import GithubIconIcon from "./icons/PlasmicIcon__GithubIcon"; // plasmic-import: 71nZrBTPy7pI/icon
import FacebookIconIcon from "./icons/PlasmicIcon__FacebookIcon"; // plasmic-import: ZGQRheiq9zwG/icon

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsnAsWzyTlUgH()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(projectcss.all, sty.freeBox__gbg8I)} />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox___57F85)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__rc9Sv)}
        >
          <IconLink
            className={classNames("__wab_instance", sty.iconLink__v8KX7)}
            icon={
              <LogoIcon
                className={classNames(projectcss.all, sty.svg__ymgi)}
                role={"img"}
              />
            }
          />

          <div className={classNames(projectcss.all, sty.freeBox___74Ko)}>
            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__iPdwt
              )}
              href={"#"}
            >
              {"Terms"}
            </a>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___94WPs
              )}
            >
              {" · "}
            </div>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__ysTbl
              )}
              href={"#"}
            >
              {"Privacy"}
            </a>
          </div>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__jwm2J)}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__u7PQ0)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xrVxQ
              )}
            >
              {"Products"}
            </div>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__oUw8N
              )}
              href={"#"}
            >
              {"Web Studio"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__i5RsI
              )}
              href={"#"}
            >
              {"DynamicBox Flex"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__diYSw
              )}
              href={"#"}
            >
              {"Programming Forms"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__u4Q2X
              )}
              href={"#"}
            >
              {"Integrations"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__dHwzh
              )}
              href={"#"}
            >
              {"Command-line"}
            </a>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__fp0Tj)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___2YiDg
              )}
            >
              {"Resources"}
            </div>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__py1Cd
              )}
              href={"#"}
            >
              {"Documentation"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__oInJ
              )}
              href={"#"}
            >
              {"Tutorials & Guides"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__fTn4P
              )}
              href={"#"}
            >
              {"Blog"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__mJcxl
              )}
              href={"#"}
            >
              {"Support Center"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__raku
              )}
              href={"#"}
            >
              {"Partners"}
            </a>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__aTaun)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__oMEzm
              )}
            >
              {"Company"}
            </div>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__mWTqd
              )}
              href={"#"}
            >
              {"Home"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__w94VP
              )}
              href={"#"}
            >
              {"About us"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__wdFp
              )}
              href={"#"}
            >
              {"Company values"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__tR9FD
              )}
              href={"#"}
            >
              {"Pricing"}
            </a>

            <a
              className={classNames(
                projectcss.a,
                projectcss.__wab_text,
                sty.link__nkFi
              )}
              href={"#"}
            >
              {"Privacy policy"}
            </a>
          </p.Stack>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__ajUgb)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___8G7LF
              )}
            >
              {"Subscribe"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__bxQde
              )}
            >
              {"Get the latest news and articles to your inbox every month."}
            </div>

            <TextInput
              data-plasmic-name={"textInput"}
              data-plasmic-override={overrides.textInput}
              className={classNames("__wab_instance", sty.textInput)}
              endIcon={
                <Button
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  color={"clear"}
                  size={"compact"}
                  startIcon={
                    <IconIcon
                      className={classNames(projectcss.all, sty.svg__erNqr)}
                      role={"img"}
                    />
                  }
                >
                  <IconIcon
                    className={classNames(projectcss.all, sty.svg__ydAwt)}
                    role={"img"}
                  />
                </Button>
              }
              fontSize={"small"}
              placeholder={"Your email"}
              showEndIcon={"showEndIcon"}
            />
          </p.Stack>
        </p.Stack>
      </p.Stack>

      <div className={classNames(projectcss.all, sty.freeBox__xsgAm)} />

      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__aq9U3)}
      >
        <div className={classNames(projectcss.all, sty.freeBox__m2DsN)}>
          <a
            className={classNames(
              projectcss.a,
              projectcss.__wab_text,
              sty.link__wbbTd
            )}
            href={"https://cruip.com/"}
          >
            {"Designed by Cruip. "}
          </a>

          <a
            className={classNames(
              projectcss.a,
              projectcss.__wab_text,
              sty.link___7FRkN
            )}
            href={"https://www.plasmic.app/"}
          >
            {"Built in Plasmic. "}
          </a>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__um1Jw
            )}
          >
            {"All rights reserved."}
          </div>
        </div>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__obcDq)}
        >
          <IconLink
            className={classNames("__wab_instance", sty.iconLink__o0JJn)}
            icon={
              <TwitterIconIcon
                className={classNames(projectcss.all, sty.svg___8Nso)}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink__hVig)}
            icon={
              <GithubIconIcon
                className={classNames(projectcss.all, sty.svg__dBuXr)}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink__iv81D)}
            icon={
              <FacebookIconIcon
                className={classNames(projectcss.all, sty.svg___4BuPs)}
                role={"img"}
              />
            }
          />
        </p.Stack>
      </p.Stack>
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "textInput", "textbox", "button"],
  textInput: ["textInput", "textbox", "button"],
  button: ["button"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textInput: makeNodeComponent("textInput"),
    button: makeNodeComponent("button"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
